Repository lost-no-more/lost-no-more-be, pull requests merged in 2025-02, with the labels that each got.

#2 [INIT] 무중단 배포 세팅 및 ci cd workflow 생성
  .github/workflows/dev-cd.yml
  .github/workflows/dev-ci.yml
  .gitignore
  Dockerfile-dev
  build.gradle
Labels: init, 🐾채원🐾

#7 [Feat] 기본 도메인, 서비스, 레포지토리 세팅
  src/main/java/org/lostnomore/backend/global/domain/BaseEntity.java
  src/main/java/org/lostnomore/backend/item/controller/LostItemController.java
  src/main/java/org/lostnomore/backend/item/domain/Category.java
  src/main/java/org/lostnomore/backend/item/domain/Location.java
  src/main/java/org/lostnomore/backend/item/domain/LostItem.java
  src/main/java/org/lostnomore/backend/item/repository/LostItemRepository.java
  src/main/java/org/lostnomore/backend/item/service/LostItemService.java
  src/main/java/org/lostnomore/backend/notification/controller/NotificationController.java
  src/main/java/org/lostnomore/backend/notification/domain/Notification.java
  src/main/java/org/lostnomore/backend/notification/domain/UserNotification.java
  src/main/java/org/lostnomore/backend/notification/repository/NotificationRepository.java
  src/main/java/org/lostnomore/backend/notification/repository/UserNotificationRepository.java
  src/main/java/org/lostnomore/backend/notification/service/NotificationService.java
  src/main/java/org/lostnomore/backend/subscribe/controller/SubscribeController.java
  src/main/java/org/lostnomore/backend/subscribe/domain/Subscribe.java
  src/main/java/org/lostnomore/backend/subscribe/repository/SubscribeRepository.java
  src/main/java/org/lostnomore/backend/subscribe/service/SubscribeService.java
  src/main/java/org/lostnomore/backend/user/controller/UserController.java
  src/main/java/org/lostnomore/backend/user/domain/SocialType.java
  src/main/java/org/lostnomore/backend/user/domain/User.java
  src/main/java/org/lostnomore/backend/user/repository/UserRepository.java
  src/main/java/org/lostnomore/backend/user/service/UserService.java
Labels: feat, dongyun

#8 [Feat] API 공통 응답 및 Exception 처리 구현
  src/main/java/org/lostnomore/backend/global/advice/GlobalExceptionHandler.java
  src/main/java/org/lostnomore/backend/global/dto/ErrorDto.java
  src/main/java/org/lostnomore/backend/global/dto/ResponseDto.java
  src/main/java/org/lostnomore/backend/global/exception/BusinessException.java
  src/main/java/org/lostnomore/backend/global/exception/code/BusinessErrorCode.java
  src/main/java/org/lostnomore/backend/global/exception/code/DefaultErrorCode.java
  src/main/java/org/lostnomore/backend/global/exception/code/ItemErrorCode.java
Labels: 🐾채원🐾, feat

#13 [TEST] 테스트 코드 기본 세팅
  src/main/java/org/lostnomore/backend/global/config/JpaConfig.java
  src/test/java/org/lostnomore/backend/common/ControllerTest.java
  src/test/java/org/lostnomore/backend/common/RepositoryTest.java
  src/test/java/org/lostnomore/backend/common/ServiceTest.java
Labels: dongyun, test

#15 [refactor] #14 모든 도메인에 빌더 생성
  src/main/java/org/lostnomore/backend/item/domain/Category.java
  src/main/java/org/lostnomore/backend/item/domain/Location.java
  src/main/java/org/lostnomore/backend/item/domain/LostItem.java
  src/main/java/org/lostnomore/backend/notification/domain/Notification.java
  src/main/java/org/lostnomore/backend/notification/domain/UserNotification.java
  src/main/java/org/lostnomore/backend/subscribe/domain/Subscribe.java
  src/main/java/org/lostnomore/backend/user/domain/User.java
Labels: refactor, dongyun

#18 [REFACTOR] 세부 오류 수정
  src/main/java/org/lostnomore/backend/global/dto/ResponseDto.java
  src/test/java/org/lostnomore/backend/common/ServiceTest.java
Labels: 🐾채원🐾, refactor

#16 [FEAT] 메인페이지 분실물 관련 조회 API 구현
  src/main/java/org/lostnomore/backend/global/domain/BaseEntity.java
  src/main/java/org/lostnomore/backend/item/controller/LostItemController.java
  src/main/java/org/lostnomore/backend/item/domain/LostItem.java
  src/main/java/org/lostnomore/backend/item/dto/response/ItemsCountDto.java
  src/main/java/org/lostnomore/backend/item/dto/response/RecentItemsDto.java
  src/main/java/org/lostnomore/backend/item/manager/LostItemRetriever.java
  src/main/java/org/lostnomore/backend/item/repository/LostItemRepository.java
  src/main/java/org/lostnomore/backend/item/service/LostItemService.java
  src/test/java/org/lostnomore/backend/item/repository/LostItemRepositoryTest.java
  src/test/java/org/lostnomore/backend/item/service/LostItemServiceTest.java
Labels: 🐾채원🐾, feat

#20 [FEAT] 소셜로그인 로직 구현
  build.gradle
  src/main/java/org/lostnomore/backend/auth/controller/AuthController.java
  src/main/java/org/lostnomore/backend/auth/dto/OAuthType.java
  src/main/java/org/lostnomore/backend/auth/dto/response/AccessTokenDto.java
  src/main/java/org/lostnomore/backend/auth/dto/response/GoogleUserDto.java
  src/main/java/org/lostnomore/backend/auth/dto/response/KakaoAccount.java
  src/main/java/org/lostnomore/backend/auth/dto/response/KakaoUserDto.java
  src/main/java/org/lostnomore/backend/auth/provider/GoogleProvider.java
  src/main/java/org/lostnomore/backend/auth/provider/KakaoProvider.java
  src/main/java/org/lostnomore/backend/auth/provider/OAuthProvider.java
  src/main/java/org/lostnomore/backend/auth/provider/OAuthProviderFinder.java
  src/main/java/org/lostnomore/backend/auth/service/AuthService.java
  src/main/java/org/lostnomore/backend/global/advice/GlobalExceptionHandler.java
  src/main/java/org/lostnomore/backend/global/config/RestTemplateConfig.java
  src/main/java/org/lostnomore/backend/global/exception/code/AuthErrorCode.java
  src/main/java/org/lostnomore/backend/global/exception/code/CommonErrorCode.java
  src/main/java/org/lostnomore/backend/user/domain/User.java
  src/main/java/org/lostnomore/backend/user/manager/UserCreator.java
  src/main/java/org/lostnomore/backend/user/manager/UserRetriever.java
  src/main/java/org/lostnomore/backend/user/repository/UserRepository.java
  src/main/java/org/lostnomore/backend/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/org/lostnomore/backend/auth/controller/AuthControllerTest.java
  src/test/resources/application-test.yml
Labels: feat, dongyun, test

#22 [FEAT] 검색 기능 구현
  .github/workflows/dev-ci.yml
  build.gradle
  src/main/java/org/lostnomore/backend/item/controller/LostItemController.java
  src/main/java/org/lostnomore/backend/item/domain/Location.java
  src/main/java/org/lostnomore/backend/item/dto/request/LostItemCreateDto.java
  src/main/java/org/lostnomore/backend/item/dto/request/LostItemIdsDto.java
  src/main/java/org/lostnomore/backend/item/dto/response/LostItemListDto.java
  src/main/java/org/lostnomore/backend/item/dto/response/LostItemsListDto.java
  src/main/java/org/lostnomore/backend/item/dto/response/LostItemsSearchDto.java
  src/main/java/org/lostnomore/backend/item/elastic/LostItemDocument.java
  src/main/java/org/lostnomore/backend/item/elastic/LostItemSearchRepository.java
  src/main/java/org/lostnomore/backend/item/elastic/LostItemSearchService.java
  src/main/java/org/lostnomore/backend/item/manager/CategoryRetriever.java
  src/main/java/org/lostnomore/backend/item/manager/LocationCreator.java
  src/main/java/org/lostnomore/backend/item/manager/LocationRetriever.java
  src/main/java/org/lostnomore/backend/item/manager/LostItemCreator.java
  src/main/java/org/lostnomore/backend/item/manager/LostItemRetriever.java
  src/main/java/org/lostnomore/backend/item/repository/CategoryRepository.java
  src/main/java/org/lostnomore/backend/item/repository/LocationRepository.java
  src/main/java/org/lostnomore/backend/item/repository/LostItemRepository.java
  src/main/java/org/lostnomore/backend/item/service/LostItemService.java
  src/test/java/org/lostnomore/backend/item/controller/LostItemControllerTest.java
  src/test/java/org/lostnomore/backend/item/service/LostItemServiceTest.java
Labels: 🐾채원🐾, feat

#25 [FIX] Jacoco 레포트 결과 출력 수정
  .github/workflows/dev-ci.yml
Labels: dongyun, fix

#23 [FEAT] JWT 기능 추가
  build.gradle
  src/main/java/org/lostnomore/backend/auth/controller/AuthController.java
  src/main/java/org/lostnomore/backend/auth/domain/RefreshToken.java
  src/main/java/org/lostnomore/backend/auth/dto/UserTokenDto.java
  src/main/java/org/lostnomore/backend/auth/provider/CookieProvider.java
  src/main/java/org/lostnomore/backend/auth/provider/JwtTokenProvider.java
  src/main/java/org/lostnomore/backend/auth/repository/RefreshTokenRepository.java
  src/main/java/org/lostnomore/backend/auth/service/AuthService.java
  src/main/java/org/lostnomore/backend/auth/util/BearerAuthorizationExtractor.java
  src/main/java/org/lostnomore/backend/global/advice/GlobalExceptionHandler.java
  src/main/java/org/lostnomore/backend/global/config/RedisConfig.java
  src/main/java/org/lostnomore/backend/global/exception/ExpiredPeriodJwtException.java
  src/main/java/org/lostnomore/backend/global/exception/InvalidJwtException.java
  src/main/java/org/lostnomore/backend/global/exception/code/AuthErrorCode.java
  src/main/java/org/lostnomore/backend/global/exception/code/BusinessErrorCode.java
  src/main/java/org/lostnomore/backend/global/exception/code/CommonErrorCode.java
  src/test/java/org/lostnomore/backend/auth/controller/AuthControllerTest.java
  src/test/java/org/lostnomore/backend/auth/provider/JwtTokenProviderTest.java
  src/test/java/org/lostnomore/backend/auth/repository/RefreshTokenRepositoryTest.java
  src/test/java/org/lostnomore/backend/auth/service/AuthServiceTest.java
  src/test/java/org/lostnomore/backend/auth/util/BearerAuthorizationExtractorTest.java
  src/test/java/org/lostnomore/backend/user/service/UserServiceTest.java
  src/test/resources/application-test.yml
Labels: feat, dongyun, test

#28 [FEAT] 분실물 검색 기능 추가 구현
  src/main/java/org/lostnomore/backend/global/exception/code/ItemErrorCode.java
  src/main/java/org/lostnomore/backend/item/controller/LostItemController.java
  src/main/java/org/lostnomore/backend/item/dto/response/LostItemDto.java
  src/main/java/org/lostnomore/backend/item/manager/LostItemRetriever.java
  src/main/java/org/lostnomore/backend/item/repository/LostItemRepository.java
  src/main/java/org/lostnomore/backend/item/service/LostItemService.java
Labels: 🐾채원🐾, feat

#30 [FEAT] 인증/인가 Interceptor 및 ArgumentResolver 생성
  src/main/java/org/lostnomore/backend/auth/provider/JwtTokenProvider.java
  src/main/java/org/lostnomore/backend/auth/service/AuthService.java
  src/main/java/org/lostnomore/backend/global/LoginUser.java
  src/main/java/org/lostnomore/backend/global/config/WebMvcConfig.java
  src/main/java/org/lostnomore/backend/global/interceptor/AccessTokenInterceptor.java
  src/main/java/org/lostnomore/backend/global/resolver/AccessTokenArgumentResolver.java
  src/test/java/org/lostnomore/backend/auth/controller/AuthControllerTest.java
  src/test/java/org/lostnomore/backend/auth/provider/JwtTokenProviderTest.java
  src/test/java/org/lostnomore/backend/auth/service/AuthServiceTest.java
  src/test/java/org/lostnomore/backend/common/ControllerTest.java
Labels: feat, dongyun

#32 [FEAT] 분실물 알림 리스트, 최근 분실물 조회 구현
  build.gradle
  src/main/java/org/lostnomore/backend/item/controller/LostItemController.java
  src/main/java/org/lostnomore/backend/item/elastic/LostItemSearchService.java
  src/main/java/org/lostnomore/backend/item/manager/LostItemRetriever.java
  src/main/java/org/lostnomore/backend/item/repository/LostItemRepository.java
  src/main/java/org/lostnomore/backend/item/service/LostItemService.java
  src/main/java/org/lostnomore/backend/subscribe/controller/SubscribeController.java
  src/main/java/org/lostnomore/backend/subscribe/domain/Subscribe.java
  src/main/java/org/lostnomore/backend/subscribe/dto/response/RecentItemsDto.java
  src/main/java/org/lostnomore/backend/subscribe/dto/response/SubscribeListDto.java
  src/main/java/org/lostnomore/backend/subscribe/manager/SubscribeRetriever.java
  src/main/java/org/lostnomore/backend/subscribe/repository/SubscribeRepository.java
  src/main/java/org/lostnomore/backend/subscribe/service/SubscribeService.java
  src/test/java/org/lostnomore/backend/item/service/LostItemServiceTest.java
  src/test/java/org/lostnomore/backend/subscribe/service/SubscribeServiceTest.java
Labels: 🐾채원🐾, feat

#33 [FEAT] 로그아웃 및 회원 탈퇴
  src/main/java/org/lostnomore/backend/auth/controller/AuthController.java
  src/main/java/org/lostnomore/backend/auth/dto/UserInfoDto.java
  src/main/java/org/lostnomore/backend/auth/dto/response/GoogleUserDto.java
  src/main/java/org/lostnomore/backend/auth/dto/response/KakaoUserDto.java
  src/main/java/org/lostnomore/backend/auth/provider/GoogleProvider.java
  src/main/java/org/lostnomore/backend/auth/provider/KakaoProvider.java
  src/main/java/org/lostnomore/backend/auth/provider/OAuthProvider.java
  src/main/java/org/lostnomore/backend/auth/service/AuthService.java
  src/main/java/org/lostnomore/backend/global/advice/GlobalExceptionHandler.java
  src/main/java/org/lostnomore/backend/global/config/WebMvcConfig.java
  src/main/java/org/lostnomore/backend/global/exception/code/AuthErrorCode.java
  src/main/java/org/lostnomore/backend/global/exception/code/BusinessErrorCode.java
  src/main/java/org/lostnomore/backend/notification/manager/UserNotificationRemover.java
  src/main/java/org/lostnomore/backend/notification/repository/UserNotificationRepository.java
  src/main/java/org/lostnomore/backend/notification/service/NotificationService.java
  src/main/java/org/lostnomore/backend/subscribe/manager/SubscribeRemover.java
  src/main/java/org/lostnomore/backend/subscribe/repository/SubscribeRepository.java
  src/main/java/org/lostnomore/backend/subscribe/service/SubscribeService.java
  src/main/java/org/lostnomore/backend/user/domain/User.java
  src/main/java/org/lostnomore/backend/user/manager/UserRemover.java
  src/main/java/org/lostnomore/backend/user/manager/UserRetriever.java
  src/main/java/org/lostnomore/backend/user/repository/UserRepository.java
  src/main/java/org/lostnomore/backend/user/service/UserService.java
  src/test/java/org/lostnomore/backend/auth/controller/AuthControllerTest.java
  src/test/java/org/lostnomore/backend/auth/provider/GoogleProviderTest.java
  src/test/java/org/lostnomore/backend/auth/service/AuthServiceTest.java
  src/test/java/org/lostnomore/backend/user/service/UserServiceTest.java
  src/test/resources/application-test.yml
Labels: feat, dongyun

#41 [FIX] 중복된 메서드 제거
  src/main/java/org/lostnomore/backend/item/manager/CategoryRetriever.java
Labels: 🐾채원🐾, fix

#39 [FEAT] 알림 관련 API 구현
  src/main/java/org/lostnomore/backend/global/exception/code/UserNotificationErrorCode.java
  src/main/java/org/lostnomore/backend/notification/controller/NotificationController.java
  src/main/java/org/lostnomore/backend/notification/domain/Notification.java
  src/main/java/org/lostnomore/backend/notification/domain/UserNotification.java
  src/main/java/org/lostnomore/backend/notification/dto/response/UserNotificationsDto.java
  src/main/java/org/lostnomore/backend/notification/manager/NotificationEditor.java
  src/main/java/org/lostnomore/backend/notification/manager/NotificationRemover.java
  src/main/java/org/lostnomore/backend/notification/manager/NotificationRetriever.java
  src/main/java/org/lostnomore/backend/notification/repository/UserNotificationRepository.java
  src/main/java/org/lostnomore/backend/notification/service/NotificationService.java
Labels: 🐾채원🐾, feat

#45 [FIX] 최근 분실물 조회 응답값에 category 추가
  src/main/java/org/lostnomore/backend/subscribe/dto/response/RecentItemsDto.java
Labels: 🐾채원🐾, fix

#47 [FEAT] 엘라스틱 서치 검색 성능 개선
  .github/workflows/dev-ci.yml
  src/main/java/org/lostnomore/backend/item/elastic/LostItemDocument.java
  src/main/java/org/lostnomore/backend/item/elastic/LostItemSearchService.java
  src/main/java/org/lostnomore/backend/item/elastic/NoriAnalyzerService.java
Labels: 🐾채원🐾, feat
